baseurl = "https://randreevdev.github.io/"
title = "riandreev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
# source config
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example
# https://github.com/luizdepra/hugo-coder/blob/main/exampleSite/hugo.toml
[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "riandreev"

[markup.highlight]
style = "monokai"

[params]
  author = "Andreev Roman"
  info = "SRE/DBRE"
  description = "My personal blog for SRE/DBRE"
  keywords = "blog,developer"
  avatarURL = "images/avatar.png"
  #gravatar = "ar1gami28@yandex.ru"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/randreevDev"

[[params.social]]
name = "Telegram"
icon = "fa-brands fa-telegram fa-2x"
weight = 1
url = "https://t.me/AndreevRI"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/johndoe/"

#[[params.social]]
#  name = "Gitlab"
#  icon = "fa-brands fa-gitlab fa-2x"
#  weight = 2
#  url = "https://gitlab.com/johndoe/"
#[[params.social]]
#  name = "Twitter"
#  icon = "fa-brands fa-x-twitter fa-2x"
#  weight = 3
#  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About me"
  weight = 2
  url = "about/"
